org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

GROUP=com.taqlyn
VERSION_NAME=0.1.0
POM_ARTIFACT_ID=taqlyn-sdk
POM_NAME=Taqlyn Android SDK
POM_DESCRIPTION=Kotlin SdkCore for Taqlyn deferred deep links, App Links, and Play Install Referrer
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/taqlyn/sdk-android
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/taqlyn/sdk-android
POM_SCM_CONNECTION=scm:git:git://github.com/taqlyn/sdk-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/taqlyn/sdk-android.git
POM_DEVELOPER_ID=taqlyn
POM_DEVELOPER_NAME=Taqlyn
POM_DEVELOPER_URL=https://github.com/taqlyn
mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true
